### PR TITLE
docs: Fix a few typos

### PR DESCRIPTION
**Pull request by timgates42**
There are small typos in:
- pyspread/commands.py
- pyspread/grid.py
- pyspread/interfaces/pys.py
- pyspread/panels.py
- pyspread/share/doc/manual/file_menu.md
- pyspread/share/doc/manual/format_menu.md
- pyspread/share/doc/manual/macro_menu.md
- pyspread/workflows.py

Fixes:
- Should read `widths` rather than `widthes`.
- Should read `target` rather than `traget`.
- Should read `synchronized` rather than `syncronized`.
- Should read `rotation` rather than `rotatation`.
- Should read `rotated` rather than `rotatated`.
- Should read `returned` rather than `retruned`.
- Should read `required` rather than `rquired`.
- Should read `recommended` rather than `recomended`.
- Should read `provided` rather than `provied`.
- Should read `progress` rather than `progess`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

### CODE REVIEW

**Comment by manns** [comment]
@timgates42 Thank you for the typo fixes. 

Please note that this repository is only an archive.
You can find the pyspread repository at https://gitlab.com/pyspread/pyspread.
Please issue the merge request there.

**Comment by pedromorgan** [comment]
@manns  Re last issue... Can i make a suggestion..  

idea is to make this repos a mirror...

1) clone/copy this `github/manns/pyspread` repos to `gitlab/pyspread/pyspread_legacy` - to keep the v1 code (which was nuked in current repos)
2) setup gitlab to mirror/push to github so their in sync

I can do step 1) but step 2) will require auth against github..

**Comment by timgates42** [comment]
Ported PR to gitlab here - https://gitlab.com/pyspread/pyspread/-/merge_requests/37

**Comment by pedromorgan** [comment]
@timgates42 Thanks.. ;-)

need to make this a mirros or something so its not as confusing

**Comment by manns** [comment]
@pedromorgan Thank you for yout quick response. My idea for hosting at both sides was to have a backup repo at another location just in case one site service stops. Therefore, your option (2) sounds better than (1). Unfortunately, I have no idea how to realize the auth against github.

I have invited you to the github repo.

**Comment by pedromorgan** [comment]
@manns So have cloned this repos..
and pushed to gitlab..
https://gitlab.com/pyspread/pyspread-v1-archive

Can u check that ?
- note some branches are missing somehow, but does it matter ??

Next step after above it to get gitlab to push to github

```
mash@kire:/home/pyspread/pyspread-v1$ git push origin --mirror
Enumerating objects: 2447, done.
Counting objects: 100% (2426/2426), done.
Delta compression using up to 4 threads
Compressing objects: 100% (1003/1003), done.
Writing objects: 100% (2359/2359), 32.32 MiB | 1.59 MiB/s, done.
Total 2359 (delta 1371), reused 2297 (delta 1318)
remote: Resolving deltas: 100% (1371/1371), completed with 36 local objects.
To gitlab.com:pyspread/pyspread-v1-archive.git
 * [new tag]           delete -> delete
 * [new tag]           v0.2.0 -> v0.2.0
 * [new tag]           v0.2.1 -> v0.2.1
 * [new tag]           v0.2.2 -> v0.2.2
 * [new tag]           v0.2.3 -> v0.2.3
 * [new tag]           v0.2.4 -> v0.2.4
 * [new tag]           v0.2.5 -> v0.2.5
 * [new tag]           v0.2.6 -> v0.2.6
 * [new tag]           v0.2.7 -> v0.2.7
 * [new tag]           v0.3.0 -> v0.3.0
 * [new tag]           v0.3.1 -> v0.3.1
 * [new tag]           v0.3.2 -> v0.3.2
 * [new tag]           v0.3.3 -> v0.3.3
 * [new tag]           v0.4 -> v0.4
 * [new tag]           v0.4.1 -> v0.4.1
 * [new tag]           v0.4.2 -> v0.4.2
 * [new tag]           v0.4.3 -> v0.4.3
 * [new tag]           v1.0 -> v1.0
 * [new tag]           v1.0.1 -> v1.0.1
 * [new tag]           v1.0.2 -> v1.0.2
 * [new tag]           v1.0.3 -> v1.0.3
 * [new tag]           v1.1 -> v1.1
 * [new tag]           v1.1.1 -> v1.1.1
 * [new tag]           v1.1.2 -> v1.1.2
 * [new tag]           v1.1.3 -> v1.1.3
 * [new tag]           v1.99.0.0 -> v1.99.0.0
 * [new tag]           v1.99.0.1 -> v1.99.0.1
 * [new tag]           v1.99.0.2 -> v1.99.0.2
 * [new tag]           v1.99.1 -> v1.99.1
 * [new tag]           v1.99.2 -> v1.99.2
 * [new tag]           v1.99.3 -> v1.99.3
 * [new tag]           v1.99.4 -> v1.99.4
 ! [remote rejected]   hub/HEAD -> hub/HEAD (deny updating a hidden ref)
 ! [remote rejected]   hub/gh-pages -> hub/gh-pages (deny updating a hidden ref)
 ! [remote rejected]   hub/master -> hub/master (deny updating a hidden ref)
 ! [remote rejected]   hub/other-master -> hub/other-master (deny updating a hidden ref)
 ! [remote rejected]   hub/python2 -> hub/python2 (deny updating a hidden ref)
 ! [remote rejected]   hub/win32 -> hub/win32 (deny updating a hidden ref)
 ! [remote rejected]   origin/master -> origin/master (deny updating a hidden ref)
error: failed to push some refs to 'git@gitlab.com:pyspread/pyspread-v1-archive.git'

```

**Comment by pedromorgan** [comment]
@manns 
Then check this page on gitlab below..
- direction is `push` ;-)
- https://gitlab.com/pyspread/pyspread/-/settings/repository
-

**Comment by manns** [comment]
I am closing this because I have integrated the fix into the development branch on gitlab.

**Pull request closed without merging**
